name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.6.0
homepage: https://github.com/pulyaevskiy/test-coverage

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  args: ^2.3.1
  coverage: ^1.6.1
  glob: ^2.1.0
  lcov_dart: ^7.0.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
