name: test_coverage
description: Command line utility to run tests in Dart VM and collect coverage data.
version: 0.5.0
homepage: https://github.com/pulyaevskiy/test-coverage
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.11.0 <3.0.0'

executables:
  test_coverage:

dependencies:
  coverage: ^0.15.2
  lcov: ^6.0.0
  glob: ^2.0.0

dev_dependencies:
  test: ^1.10.0
  pedantic: ^1.7.0
